### ISSUE TITLE
建议帮助文档在安装sass-loader的时候指明版本号

### ISSUE THREAD

**Issue by TOP-LH** [auven/vant-weapp-convert-uniapp#4]
建议帮助文档在安装sass-loader的时候指明版本号，如果不指名使用最新版的话会无法启动项目。
  另外想问一下作者还更新吗?

**Comment by auven** [comment]
感谢关注，由于能力有限，目前没计划更新。推荐两个还不错的组件，目前有在项目中使用的：
- [uView](https://www.uviewui.com/)
- [ThorUI](https://thorui.cn/doc/)
